import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { fetchRecommendations } from "@/lib/api";
import { AnimeRow } from "@/components/anime-row";
import { Sparkles, Brain, Zap, Heart, Loader2, Info } from "lucide-react";
import type { Anime } from "@/lib/mock-anime";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/recommendations")({
  head: () => ({ meta: [{ title: "Recommendations — ReccoFlix" }] }),
  component: RecsPage,
});

function RecsPage() {
  const [data, setData] = useState<{ recommendations: Anime[], source: string, message: string }>({ 
    recommendations: [], 
    source: "trending",
    message: "" 
  });
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchRecommendations()
      .then(res => {
        setData(res);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex h-[80vh] items-center justify-center">
        <Loader2 className="h-12 w-12 animate-spin text-primary" />
      </div>
    );
  }

  const isAI = data.source === "ai";

  return (
    <div className="space-y-12">
      <header className={cn(
        "relative overflow-hidden rounded-3xl border p-8 shadow-glow transition-all duration-700 sm:p-12",
        isAI ? "border-primary/20 bg-gradient-purple/30 shadow-glow-purple" : "border-white/10 bg-gradient-to-br from-white/5 to-transparent"
      )}>
        <div className="absolute right-0 top-0 h-48 w-48 -translate-y-12 translate-x-12 rounded-full bg-primary/30 blur-3xl opacity-50" />
        
        <div className="relative max-w-2xl">
          <div className={cn(
            "inline-flex items-center gap-2 rounded-full px-4 py-1.5 text-[10px] font-bold uppercase tracking-[0.2em] backdrop-blur",
            isAI ? "bg-primary text-primary-foreground shadow-glow" : "bg-white/10 text-muted-foreground"
          )}>
            {isAI ? <Sparkles className="h-3.5 w-3.5" /> : <Info className="h-3.5 w-3.5" />}
            {isAI ? "Generated by ReccoFlix AI" : "Discovery Mode"}
          </div>

          <h1 className="mt-6 text-3xl font-extrabold sm:text-5xl lg:text-6xl">
            {isAI ? (
              <>Picks tailored for <span className="text-gradient-primary">you</span></>
            ) : (
              <>Community <span className="text-gradient-primary">Discovery</span></>
            )}
          </h1>
          
          <p className="mt-4 max-w-lg text-sm text-muted-foreground sm:text-base leading-relaxed">
            {isAI 
              ? "Our AI analyzed your watch history and found these hidden gems and hits specifically for your taste."
              : "Start adding anime to your library! Once you have at least 1 show, our AI can start building personalized picks for you."
            }
          </p>
        </div>
      </header>

      {data.recommendations.length > 0 ? (
        <div className="space-y-16">
          <AnimeRow
            title={isAI ? "Your Top Matches" : "Community Favorites"}
            subtitle={isAI ? "High-precision picks based on your profile" : "Popular shows to get you started"}
            anime={data.recommendations.slice(0, 8)}
            showMatch={isAI}
            accent={isAI ? "purple" : "primary"}
          />

          {isAI && (
            <AnimeRow
              title="Deeper Discoveries"
              subtitle="Hidden gems you might have missed"
              anime={data.recommendations.slice(8)}
              showMatch
              accent="cyan"
            />
          )}
        </div>
      ) : (
        <div className="glass rounded-3xl p-20 text-center">
          <Brain className="mx-auto h-12 w-12 text-muted-foreground/30 mb-4" />
          <p className="text-lg font-bold text-foreground">AI is warming up...</p>
          <p className="text-sm text-muted-foreground mt-1">Check back in a moment or add more anime to your list.</p>
        </div>
      )}

      {/* Mood-based — Link to dedicated page */}
      <section>
        <h2 className="mb-6 flex items-center gap-2 text-xl font-bold">
          <Zap className="h-5 w-5 text-primary" /> Pick a mood
        </h2>
        <Link to="/mood" className="grid grid-cols-2 gap-4 sm:grid-cols-4">
          {[
            { label: "Cozy", emoji: "☕", glow: "shadow-glow-success", color: "text-success" },
            { label: "Action Rush", emoji: "⚡", glow: "shadow-glow", color: "text-primary" },
            { label: "Romantic", emoji: "💖", glow: "shadow-glow-pink", color: "text-pink" },
            { label: "Mind-bending", emoji: "🧠", glow: "shadow-glow-purple", color: "text-purple" },
          ].map((m) => (
            <div key={m.label} className={cn("glass group rounded-2xl p-6 text-left transition-smooth hover:-translate-y-1.5", m.glow)}>
              <div className="text-4xl transition-transform group-hover:scale-110">{m.emoji}</div>
              <div className="mt-3 font-bold">{m.label}</div>
              <div className={cn("text-[10px] font-bold uppercase tracking-wider", m.color)}>AI Curated</div>
            </div>
          ))}
        </Link>
      </section>

      {isAI && (
        <section className="glass-strong relative overflow-hidden rounded-3xl p-10 text-center border border-primary/10">
          <div className="absolute -left-10 -top-10 h-32 w-32 bg-primary/20 blur-3xl" />
          <Sparkles className="mx-auto h-10 w-10 text-primary" />
          <h3 className="mt-4 text-2xl font-bold">Your AI gets smarter every day</h3>
          <p className="mt-2 mx-auto max-w-md text-sm text-muted-foreground">Every rating and every "Completed" show sharpens your recommendation profile.</p>
          <button className="mt-6 inline-flex items-center gap-2 rounded-full bg-gradient-primary px-8 py-3.5 text-sm font-bold text-primary-foreground shadow-glow transition-smooth hover:scale-105">
            <Heart className="h-4 w-4 fill-current" /> Keep Discovering
          </button>
        </section>
      )}
    </div>
  );
}
