/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as DossierIdEpisodeNumRouteImport } from './routes/dossier.$id.$episodeNum'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/archive/$id',
  path: '/archive/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIdEpisodeNumRoute = DossierIdEpisodeNumRouteImport.update({
  id: '/dossier/$id/$episodeNum',
  path: '/dossier/$id/$episodeNum',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dossier/$id/$episodeNum': typeof DossierIdEpisodeNumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dossier/$id/$episodeNum': typeof DossierIdEpisodeNumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/browse': typeof BrowseRoute
  '/favorites': typeof FavoritesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/mood': typeof MoodRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/archive/$id': typeof ArchiveIdRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/dossier/$id/$episodeNum': typeof DossierIdEpisodeNumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/browse'
    | '/favorites'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mood'
    | '/privacy'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/anime/$id'
    | '/archive/$id'
    | '/reset-password/$token'
    | '/dossier/$id/$episodeNum'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/browse'
    | '/favorites'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mood'
    | '/privacy'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/anime/$id'
    | '/archive/$id'
    | '/reset-password/$token'
    | '/dossier/$id/$episodeNum'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/browse'
    | '/favorites'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/mood'
    | '/privacy'
    | '/profile'
    | '/recommendations'
    | '/search'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/anime/$id'
    | '/archive/$id'
    | '/reset-password/$token'
    | '/dossier/$id/$episodeNum'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrowseRoute: typeof BrowseRoute
  FavoritesRoute: typeof FavoritesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  MoodRoute: typeof MoodRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AnimeIdRoute: typeof AnimeIdRoute
  ArchiveIdRoute: typeof ArchiveIdRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
  DossierIdEpisodeNumRoute: typeof DossierIdEpisodeNumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/archive/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$id/$episodeNum': {
      id: '/dossier/$id/$episodeNum'
      path: '/dossier/$id/$episodeNum'
      fullPath: '/dossier/$id/$episodeNum'
      preLoaderRoute: typeof DossierIdEpisodeNumRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrowseRoute: BrowseRoute,
  FavoritesRoute: FavoritesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  MoodRoute: MoodRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AnimeIdRoute: AnimeIdRoute,
  ArchiveIdRoute: ArchiveIdRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
  DossierIdEpisodeNumRoute: DossierIdEpisodeNumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
