name: Deploy ReccoFlix to EC2

on:
  push:
    branches:
      - main  # This triggers the deployment only when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Load the full environment (helps find npm, npx, and pm2)
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            source ~/.profile || source ~/.bashrc

            cd /home/${{ secrets.EC2_USERNAME }}/ReccoFlix
            
            # 2. Force a clean state (discard any local server changes)
            git fetch origin main
            git reset --hard origin/main
            
            # 3. Recreate the .env file
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # 4. Install & Generate
            npm install
            npx prisma generate
            
            # 5. Restart
            pm2 restart index.js || pm2 start index.js --name "reccoflix"


