name: Deploy ReccoFlix to EC2

on:
  push:
    branches:
      - main  # This triggers the deployment only when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USERNAME }}/ReccoFlix
            
            # 1. Pull the latest code
            git fetch origin main
            git reset --hard origin/main
            
            # 2. Recreate the .env file
            echo "${{ secrets.ENV_FILE }}" > .env
            
            # 3. Build and Start the container
            # Using 'docker compose' (modern) instead of 'docker-compose'
            sudo docker compose up -d --build --remove-orphans
            
            # 4. CRITICAL: Cleanup old "junk" images to save EBS space
            sudo docker image prune -f




